services:
  database:
    container_name: database
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dpe_api
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - ./docker-build/mysql:/var/lib/mysql

  php-fpm:
    container_name: MYSITE_PHP_SERVER
    image: theva/php-fpm:8.2
    volumes:
      - ./app:/var/www/symfony:rw
    depends_on:
      - database

  nginx:
    image: nginx:1.26.0-alpine
    restart: always
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/symfony.conf:/etc/nginx/sites-enabled/symfony
      - ./app:/var/www/symfony
    ports:
      - 80:80
    depends_on:
      - php-fpm
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - 8081:80
    depends_on:
      - database